### ISSUE TITLE
Assertion Failure when running through the Terminal

### ISSUE THREAD

**Issue by saru2020** [appium/screen_recording#5]
Assertion failed: (did_initialize), function CGS_REQUIRE_INIT, file Desktop/CGInitialization.c, line 40.
Abort trap: 6

Any suggestion?

**Comment by Simon-Kaz** [comment]
I'm getting the same error, any clues?

**Comment by Simon-Kaz** [comment]
I've been told that it might be because of the update to xcode 6 - I can't downgrade, so maybe someone could test that? It's a core graphic error, so something fundamental went wrong...

**Comment by saru2020** [comment]
Exactly.
I just tried it in Xcode5.1 and the build succeeds.
Hope it must fixed in the latest versions.

**Comment by bootstraponline** [comment]
I confirm it's broken on xcode 6. I don't use this project anymore so I probably won't have time to update it. The line of code that's failing is from square's [zapp](https://github.com/square/zapp) project which hasn't been updated since 2011. I'll ask around to see if someone on the team is more familiar with objective c and could fix the issue. The API probably changed which is why it's crashing.

**Comment by bootstraponline** [comment]
I updated the repo to [clarify the maintenance status](https://github.com/appium/screen_recording/commit/a56e5b9a1b8872b55e885b35cfb572e2de0c89b3). It's all open source so maybe someone will fix it in the future.

**Comment by bootstraponline** [comment]
https://github.com/appium/screen_recording/pull/6
